### ISSUE TITLE
First input ignored when console open

### ISSUE THREAD

**Issue by marvinroger** [romanov/MonoGame-Console#7]
Hi,

Thanks for the useful project!

I encounter an issue though: whenever I open the console and input something, the first character is always ignored. In other words, I have to press on any key on the keyboard once before being able to input things to the console.

Thanks!

**Comment by romanov** [comment]
Hello,

please, provide information about your system (OS, system language).

Check that some apps are not interfering with the input.

**Comment by marvinroger** [comment]
**OS:** Windows 10 x64
**MonoGame Windows DX**: 3.5.1.1679
**.Net**: 4.5.1
**System language:** French

I don't have anything interfering with the input, every other apps work fine. Also, key events work fine in the code.

**Comment by romanov** [comment]
A little quick update from me: this is a very strange behaviour, but i think we should look into System.Windows.Forms. I will try to find some time to update & decouple key capture from WIndows.Forms to MonoGame's default KeyInput.

It will take some time because XNA/MonoGame KeyInput is not working with unicode chars by default.

**Comment by marvinroger** [comment]
Sorry for the delay!

I just tried with a new empty project, with the demo code on the README, and I experience the same behavior: I need to type any key once before the input gets written to the console.
